### ISSUE TITLE
Simple question about server use

### ISSUE THREAD

**Issue by CapBlackShot** [nearbear/ValheimBepinexMods#10]
Hi there,

If I want to use the plugin on my dedicated server, do I have to install it only under the server's directory, only under the game's folder, or both?

I never really know when to install things locally or on both sides for Valheim.

Thank ya!

**Comment by nearbear** [comment]
Which mod are you referring to? There are multiple in this repo.

I know all of my mods besides except one need to be installed on the client only, server doesn't matter. Vengeful Trees is the one I'm not sure about, haven't tried.

**Comment by CapBlackShot** [comment]
> Which mod are you referring to? There are multiple in this repo.
> 
> I know all of my mods besides except one need to be installed on the client only, server doesn't matter. Vengeful Trees is the one I'm not sure about, haven't tried.

BiggerBoatMapExploreRadius is the one I'm talking about. Sorry for not mentioning it before.

Can I install it on the server instead of the client though? Will it work for everybody that joins or will they need the mod installed on their clients too? Or server doesn't matter at all? @nearbear
