### ISSUE TITLE
Suggestion: can you make it so only the sea and the shoreline is revelaed with the extended range?

### ISSUE THREAD

**Issue by EstebanLB** [nearbear/ValheimBepinexMods#11]
Suggestion: can you make it so only the sea and the shoreline is revelaed with the extended range?

**Comment by nearbear** [comment]
I'm sorry but this mod is unmaintained, I won't be updating it.

that being said I did have this idea when I first made the mod, but it would have been much more complex than a simple radius increase. I'm surprised it's not in the game yet tbh.
