### ISSUE TITLE
Better AutoRun - continue running/sprinting after jumping

### ISSUE THREAD

**Issue by gittywithexcitement** [nearbear/ValheimBepinexMods#8]
Very useful mod, thank you for sharing! Before you released it, I had some janky AutoHotkey script to do autosprint and keep sprinting after strafing, but it didn't work very well. So you definitely saved me some trouble, thanks!

Would it be possible to continue sprinting after jumping? When running around, I occasionally need to jump an obstacle and would like to keep running or sprinting, without having to press Q again. That would be a nice little QOL improvement. 

Thanks for consideration.

**Comment by nearbear** [comment]
Yes, that sounds reasonable. Shouldn't be too difficult to do, either.

**Comment by nearbear** [comment]
Included the changes in version 1.0.3. Glad you enjoyed the mod, thanks for the suggestion!

**Comment by gittywithexcitement** [comment]
I tried it out, and it works like a charm. Thanks a bunch!
